name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

env:
  UPSTREAM_REPO: ourongxing/chatgpt-vercel
  UPSTREAM_BRANCH: main

jobs:
  merge:
    name: Merge Upstream into Fork
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          repository: ${{ env.REPO }}
      - name: Fetch Upstream
        run: |
          git remote add upstream https://github.com/${{ env.UPSTREAM_REPO }}.git
          git fetch upstream
      - name: Merge Upstream into Fork
        run: |
          git fetch
          git merge --strategy=ort -X patience ${{ env.UPSTREAM_BRANCH }} -m "合并上游变更"
          git push
